title: Kyle McCarthy # your name (or website title) here
logo: "/images/me.PNG?raw=true" # your photo (or logo) here
description: 
Education
<br> 
Masters Urban Spatial Analytics @ University of Pennsylvania, 2021
<br> 
B.S Geology with minors in Geography and Geospaital Technologies @ Unviersity of Vermont, 2020
  <br><br>
  <a href="www.linkedin.com/in/kyle-mccarthy-9338a8177">View My LinkedIn Profile</a> 
  <br> 
  <a href="https://drive.google.com/file/d/1TWhnNVjqKauBx1Z6r2TPx30UOftOJus2/view?usp=sharing">View My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
