title: About Me # your name (or website title) here

html_document:
  toc: yes
  toc_float: yes
logo: "/images/me.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
 
  I am a data science professional interested in utilizing data to solve social, economic, and environmental dilemmas. I have a background in geosciences, human geography, and urban planning, where I have learned to solve many spatial analytical problems. I have developed a variety of programming skills, GIS skills, and remote sensing skills suitable to a large variety of industries. I can be of great help in various fields, including machine learning, web development, GIS, environmental science, and city planning. 
  <br><br>
  <a href="https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile">View My LinkedIn Profile</a> 
  <br>
  <a href="https://drive.google.com/file/d/1gmN4QUH86-8mWd7eWENMFGQdOwyrvPUx/view?usp=sharing">View My Resume</a>
  <br> 
  Email : kyle.p.mccarthy97@gmail.com
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
